name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: taiki-e/install-action@cargo-hack
    - name: hmm
      run: ls
    - name: build
      run: cargo hack build --feature-powerset
    - name: test
      run: cargo hack test --feature-powerset
  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: fmt
      run: cargo fmt --check
